### ISSUE TITLE
Call failed: An error occured while sending the request get api.pro.coinbase/accounts

### ISSUE THREAD

**Issue by kevinfreemanindustries** [bchavez/Coinbase.Pro#14]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| NuGet Package            |     2.06     |
| .NET Core?                   |     4.5.2     |
| .NET Full Framework?   |                 |
| Windows OS?              |   WIN 10   |
| Linux OS?                    |                  |
| Visual Studio?              |                 |

### What's the problem?
I get an error when trying to access the account

The error says Call failed: An error occurred while sending the request get api.pro.coinbase/accounts

I am using the following code:
try
            {
                client = new CoinbaseProClient(new Config
                {
                    ApiKey = clientForma[0],
                    Secret = clientForma[1],
                    Passphrase = clientForma[2],
                });
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Error: ", MessageBoxButton.OK);
            }
try
            {
                var Account = await client.Accounts.GetAllAccountsAsync();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Error: ", MessageBoxButton.OK);
            }

I do not receive an error when connecting to the client, but receive an error when accessing the accounts

### What possible solutions have you considered? 
I tried updating all the nuget packages same error

### Do you have sample code to show what you're trying to do?
try
            {
                client = new CoinbaseProClient(new Config
                {
                    ApiKey = clientForma[0],
                    Secret = clientForma[1],
                    Passphrase = clientForma[2],
                });
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Error: ", MessageBoxButton.OK);
            }
try
            {
                var Account = await client.Accounts.GetAllAccountsAsync();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Error: ", MessageBoxButton.OK);
            }
_(Please be complete. Include any class models necessary to run your code.)_

### What is the HTTP request JSON and response JSON?

_(Use Fiddler to help capture this information)_

**Comment by bchavez** [comment]
Hi Kevin,

I think in order for me to help you you'll need to provide some traffic examples of the responses you're getting from your API call.

Here's how to debug API traffic from the Coinbase library and your app:
https://github.com/bchavez/Coinbase/wiki/Debugging-with-Fiddler

Then post the JSON response here, but take out/remove/redact any personally identifiable information and I can try to see what when wrong.

Also, if you could provide a stack trace of the exception that occurred, that would be great.

Thanks,
Brian

**Comment by kevinfreemanindustries** [comment]
Hello,

How do you dump var Account = await client.Accounts.GetAllAccountsAsync(); 

I am having trouble connecting to api.pro.coinbase.com the HTTP Response is...

fiddler.network.https> HTTPS handshake to api.pro.coinbase.com (for #1) failed. System.Security.Authentication.AuthenticationException A call to SSPI failed, see inner exception. < The function requested is not supported

Win32 (SChannel) Native Error Code: 0x80090302

I set up Fiddler as shown in the guide in your post. I see no HTTPS  Responses, all that I see is two 200 HTTP Responses

**Comment by bchavez** [comment]
Hi @kevinfreemanindustries, 

>0x80090302
> This error can occur when the component is using an older version of TLS, but the server requires a newer version. For instance if the component is using TLS 1.0, but the server requires TLS 1.2, you can see this error. Older versions of the components may not have the newer protocols enabled by default. In the current versions TLS 1.2 is enabled by default.
> https://www.nsoftware.com/kb/xml/06101501.rst#:~:text=0x80090302,you%20can%20see%20this%20error.

You'll need to ensure your application is using TLS 1.2. Any version below TLS 1.2 is unlikely to work; hence the error.

Please see the minimum requirements note here:
https://github.com/bchavez/Coinbase.Pro#minimum-requirements

**Comment by bchavez** [comment]
Feel free to reopen the issue if you can provide more technical details after you've tried ensuring that TLS 1.2 is being used. Thanks.
