### ISSUE TITLE
Cannot connect to webservice feed.

### ISSUE THREAD

**Issue by salocinx** [bchavez/Coinbase.Pro#15]
Hi

Thanks for sharing your work! I am currently trying to connect to the websocket feed. But `await socket.ConnectAsync();` never returns and I get not connected. I have double checked the webservice at `wss://ws-feed-public.sandbox.pro.coinbase.com` on [www.websocket.org](https://www.websocket.org/echo.html) and the webservice itself seems to be working fine.

Here's my testing code:

```
using System;
using System.IO;
using System.Collections.Generic;

using WebSocket4Net;

using Coinbase.Pro;
using Coinbase.Pro.Models;
using Coinbase.Pro.WebSockets;

using System.Threading.Tasks;

namespace WebsocketFeed {

    public class Program {

        private bool sandbox = true;

        private string apiKey = "<my-api-key>";
        private string secret = "<my-api-secret>";
        private string passphrase = "<my-api-passphrase>";

        private CoinbaseProWebSocket socket;

        public static void Main(string[] args) {
            Program p = new Program();
            p.InitializeCoinbasePro();
            p.InitializeWebsocketFeed();
            Console.WriteLine("Press any key to exit ...");
            Console.ReadLine();
        }

        private void InitializeCoinbasePro() {
            if(sandbox) {
                this.socket = new CoinbaseProWebSocket(new WebSocketConfig {
                    ApiKey = apiKey,
                    Secret = secret,
                    Passphrase = passphrase,
                    SocketUri = "wss://ws-feed-public.sandbox.pro.coinbase.com"
                });
            } else {
                this.socket = new CoinbaseProWebSocket(new WebSocketConfig {
                    ApiKey = apiKey,
                    Secret = secret,
                    Passphrase = passphrase
                });
            }
        }

        private async Task InitializeWebsocketFeed() {
            // Connect websocket.
            Console.WriteLine("Connecting to websocket feed ... ");
            await socket.ConnectAsync();
            Console.WriteLine("[OK]");
            // Initialize event handler.
            socket.RawSocket.MessageReceived += RawSocket_MessageReceived;
            // Create a subscription of what to listen to.
            var sub = new Subscription {
                ProductIds = {
                    "ETH-USD",
                },
                Channels = {
                    "heartbeat",
                }
            };
            // Send the subscription upstream.
            await socket.SubscribeAsync(sub);
            // Now wait for data.
            await Task.Delay(TimeSpan.FromMinutes(1));
        }

        private void RawSocket_MessageReceived(object sender, MessageReceivedEventArgs e) {
            // Try parsing the e.Message JSON.
            if(WebSocketHelper.TryParse(e.Message, out var msg)) {
                if(msg is HeartbeatEvent hb) {
                    Console.WriteLine($"Last Trade ID: {hb.LastTradeId}");
                }
            }
        }

    }

}
```

The code line `Console.WriteLine("[OK]");` is never executed. The program hangs at `await socket.ConnectAsync();` infinitely.

Some idea how to solve this issue?

**Comment by bchavez** [comment]
Hi @salocinx ,

Can you double-check? I just tried executing your code example and it seems to work fine:
![image](https://user-images.githubusercontent.com/478118/86478390-0bddf780-bcff-11ea-9f47-ff5d1646b64c.png)

It did take a few seconds to connect, but connected nonetheless.

**Comment by bchavez** [comment]
Also, Nicolas, note that `ETH-USD` fiat market doesn't exist on Sandbox (and consequently, no heartbeat for `ETH-USD`). Try using `BTC-USD` for Sandbox if you're looking for a `heartbeat`. The `ETH-USD` fiat market you're looking for only exists on **Production** (currently).

![image](https://user-images.githubusercontent.com/478118/86479943-f0282080-bd01-11ea-8415-d7cb33109960.png)

Products API on Sandbox: https://api-public.sandbox.pro.coinbase.com/products
```json
{
    "id": "LINK-USDC",
    "base_currency": "LINK",
    "quote_currency": "USDC",
    ...
  },
  {
    "id": "BAT-USDC",
    "base_currency": "BAT",
    "quote_currency": "USDC",
    ...
  },
  {
    "id": "ETH-BTC",
    "base_currency": "ETH",
    "quote_currency": "BTC",
    ...
  },
  {
    "id": "BTC-USD",
    "base_currency": "BTC",
    "quote_currency": "USD",
    ...
  },
  {
    "id": "BTC-GBP",
    "base_currency": "BTC",
    "quote_currency": "GBP",
    ...
  },
  {
    "id": "BTC-EUR",
    "base_currency": "BTC",
    "quote_currency": "EUR",
    ...
  }
]
```
Changing the product ID to the `BTC-USD` market on Sandbox shows a `heartbeat`:

![image](https://user-images.githubusercontent.com/478118/86479646-6415f900-bd01-11ea-80c2-984b1213f9bc.png)

Let me know if you continue to have issues.

Thanks,
Brian

**Comment by salocinx** [comment]
Hi Brian

Thank you very much for your detailed answer! I still cannot connect when using the [NuGet package 2.0.6](https://www.nuget.org/packages/Coinbase.Pro/). My sample program never outputs `[OK]`, which means that `await socket.ConnectAsync();` never returns. I meanwhile also tried to turn off all firewalls from Windows and make sure the web service isn't blocked by the router's firewall as well.

However, I now cloned your [master branch](https://github.com/bchavez/Coinbase.Pro) and imported my sample program there and it works exactly like you describe in your answer (getting heartbeat messages for `BTC-USD` on sandbox).

Is there any difference between the NuGet package 2.0.6 and the current master branch on GitHub?

Thanks for your support!
Nicolas

**Comment by bchavez** [comment]
Hi Nicolas,

No there shouldn't be any functional difference between `v2.0.6` on NuGet and the `master` branch here.

The only thing I can think of that might make a difference is that:
* You'd want to make sure that your project is binding to the correct TFM. If you open the NuGet package with a zip utility, you should have 2 folders:

  ![image](https://user-images.githubusercontent.com/478118/86851670-36fe7900-c068-11ea-9115-1bde79074db0.png)

  One is a build for .NET Framework 4.5 and the other is for .NET Standard 2.0. You'll want to check that you're program is linked to and using the correct TFM.

* Also, try deleting any `/bin` and `/obj` folders; and then recompiling.

It's hard to tell what exactly is going on without more diagnostic information from your machine. If you'd like more help, please provide:

* Operating System and version.
* What are you using for your service? .NET Framework or .NET Core? What versions?
* Provide some Wireshark traces between your machine and Coinbase (be careful of sensitive info here)
* Have you tried using the `.EnableFiddlerDebugProxy()`? If so, do you see any errors? More info here: https://github.com/bchavez/Coinbase/wiki/Debugging-with-Fiddler

Thanks,
Brian

**Comment by bchavez** [comment]
Hi @salocinx, I took a second look at this and was able to reproduce the issue. The problem is, the event that fires `.Opened` event is the main thread for `WebSocket4Net` and messages won't be processed when the tread blocks at `.ReadLine()`. So it's like we stole the thread from `WebSocket4Net` and it never processes messages again.

I'm going to try to fix the bug and release a new version with a possible bug fix.

**Comment by bchavez** [comment]
Hi @salocinx 

Please try `v3.0.1` I think I've included some fixes that might help your situation on .NET Full Framework.
https://www.nuget.org/packages/Coinbase.Pro/3.0.1
