### ISSUE TITLE
L2UpdateEvent is missing "Time" -property

### ISSUE THREAD

**Issue by pohjao** [bchavez/Coinbase.Pro#24]
Hello and thank you for the great job done with this library!

[Coinbase Pro documentation](https://docs.pro.coinbase.com/#the-level2-channel) states that `l2update`s have a `time` property stating the time of the recorded event.

The library's L2UpdateEvent declaration is following (missing the `Time` property):
```
public class L2UpdateEvent : Event
{
	[JsonProperty ("product_id")]
	public string ProductId {
		get;
		set;
	}

	[JsonProperty ("changes", ItemConverterType = typeof(L2UpdateChangeConverter))]
	public List<L2UpdateChange> Changes {
		get;
		set;
	}
}

public class Event : Json
{
	[JsonProperty ("type")]
	public string Type {
		get;
		set;
	}
}
```

Please let me know if you wish to receive code contributions regarding this issue.

**Comment by bchavez** [comment]
Hi @pohjao, 

Thanks for the heads up. 

Yeah, their object model changes all the time. As a workaround, you can always use the `.ExtraJson` property to access any JSON fields that aren't parsed into the object model. In other words, `L2UpdateEvent.ExtraJson["time"]` should get you access to the time property on the `L2UpdateEvent` object even though it's not explicitly parsed into a C# property.

Please feel free to send a PR and reference this issue number. I'll try to get a new release out this weekend.

Thanks,
Brian

**Comment by bchavez** [comment]
New version published: https://www.nuget.org/packages/Coinbase.Pro/3.3.0

Let me know how it goes!
