### ISSUE TITLE
Error in module OrderSide.Buy

### ISSUE THREAD

**Issue by silentone-one** [bchavez/Coinbase.Pro#31]
Hi, bChavez, 

I have a tiny question and a beginner in C #, anyway during testing with the Coinbase Pro Sandbox and your Coinbase.pro 
For the moment I ran into the buy option issues not being accepted: 

"Call failed with status code 400 (Bad Request): POST https://api-public.sandbox.pro.coinbase.com/orders"

Code
client.Orders.PlaceLimitOrderAsync(OrderSide.Buy, "BTC-EUR", size: sizeround, limitPrice: limitPriceRound, timeInForce: TimeInForce.GoodTillCanceled);

I assume the API works fine to get Fills & Sell Orders.

Kind Regards,

**Comment by bchavez** [comment]
Hi @silentone-one, in order to get more insight into the problem, I suggest debugging the issue with Fiddler. See: https://github.com/bchavez/Coinbase/wiki/Debugging-with-Fiddler

You'll need to call `.EnableFiddlerDebugProxy()` on the client to tunnel requests through Fiddler for inspection.

Then let me know what you find when you make the request.

**Comment by silentone-one** [comment]
Hi Brian,

Just started the Proxy Software, I assume a package has to be installed in
order to communicate with the Fiddler Proxy from the program client.

Cheers,

Op zo 17 jan. 2021 om 18:51 schreef Brian Chavez <notifications@github.com>:

**Comment by silentone-one** [comment]
Hi,

FYI found the issue. Thanks for the help

Kind regards

Op zo 17 jan. 2021 om 19:09 schreef Jo Becaus <jo.becaus@gmail.com>:

**Comment by alessandroparma** [comment]
Ouch!
Got the same error on the same /order page. 
What was the error? And what the solution?

**Comment by renaudLVLP** [comment]
@silentone-one I do have the same issue as well. Could you provide the solution ? @bchavez maybe could you re-open the topic until sharing a solution. Same error : "Call failed with status code 400 (Bad Request): POST https://api-public.sandbox.pro.coinbase.com/orders" while calling the method PlaceLimitOrderAsync size 1 and price 38948 as an example.

But I do occasionally see an order succeeding and I do not know why.

Cheers ;)
