### ISSUE TITLE
Product base_increment

### ISSUE THREAD

**Issue by minskowl** [bchavez/Coinbase.Pro#34]
Hello

Product has such base_increment field  (https://docs.pro.coinbase.com/#get-products)

but  Coinbase.Pro.Models.Product doesn't have such field.
Please add it

**Comment by bchavez** [comment]
Thanks for posting. I'll try to review this over the weekend.

**Comment by bchavez** [comment]
**Coinbase.Pro** `v4.1.1` released with updated `Product` model: https://www.nuget.org/packages/Coinbase.Pro/4.1.1
