### ISSUE TITLE
 Cardano symbol ADAUSD  

### ISSUE THREAD

**Issue by bwjunkie** [bchavez/Coinbase.Pro#43]
currency type Cardano symbol ADAUSD

**Comment by bchavez** [comment]
Hi Josh, what about ADAUSD? You should be able to use the `Coinbase.Pro` library with ADAUSD without issue. The product IDs in the library API are `string`; so, specifying a product ID of `ADA-USD` should work.

Let me know if there's any issue.

**Comment by bwjunkie** [comment]
ah yes I see that now.  working good, thanks!

**Comment by bchavez** [comment]
No problem. You can always get a list of the current product IDs from Coinbase Pro by using the `client.MarketData.GetProductsAsync()` method as shown below:

![image](https://user-images.githubusercontent.com/478118/111912509-27249a80-8a27-11eb-92b3-03b23d2df5ff.png)

If you want to get supported products only available on **Sandbox** use the **Sandbox** URL as shown below:

![image](https://user-images.githubusercontent.com/478118/111912664-dfead980-8a27-11eb-8947-9cc56716dcbd.png)
