### ISSUE TITLE
Conversion

### ISSUE THREAD

**Issue by PeterLAxakon** [bchavez/Coinbase.Pro#48]
### What's the problem?
I'm trying to use the endpoint for conversion --> response 400
I do have a CoinbasePro account with ETH.

### What possible solutions have you considered? 
I cant seem to find whats wrong. 400 indicates my parameters are wrong?
Is the format wrong? ID what is that(currency code?), the example I'm looking at is using USDC.
Amount is using datatype decimal, should it have some sort of formating to it ? 
The url in the response does not contain any paramters, guessing data is send via the body?
Amount, what currency should this be in ? 

### Do you have sample code to show what you're trying to do?
FromId: ETH 
ToId: BCH 
Amount: 10 (also tried with from currency(ETH in this case)) 
 ```
public async Task<Coinbase.Pro.Models.Conversion> Convert(string fromId, string toId, decimal amount)
        {
            //   from:
            //     Currency Id
            //
            //   to:
            //     Currency id
            //
            //   amount:
            //     Amount of from to convert to to
            try
            {
          
                return await client.Conversion.ConvertAsync(fromId, toId, amount);

            }
            catch (Exception ex)
            {
                return null;
            }
        }
```

### What is the HTTP request JSON and response JSON?
Response 400: Call failed with status code 400 (Bad Request): POST https://api.pro.coinbase.com/conversions

**Comment by bchavez** [comment]
The `/conversion` endpoint is for **_stablecoin_** conversions; not asset conversions like ETH->BCH. https://docs.pro.coinbase.com/#stablecoin-conversions

If you want USDC, you need to:
* **Sell** ETH for USDC with ETH-USDC trading pair.

If you want BCH, you need to:
* **Sell** ETH for USD with ETH-USD trading pair.
* Use USD to **_Buy_** BCH with BCH-USD trading pair.

**Comment by PeterLAxakon** [comment]
Thank you for clarifying that ang giving examples
