### ISSUE TITLE
Com Server Call results in "The request was aborted: Could not create SSL/TLS secure channel"

### ISSUE THREAD

**Issue by raderag** [bchavez/Coinbase.Pro#50]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| NuGet Package            |         4.1.2        |
| .NET Core?                   |                 |
| .NET Full Framework?   |     4.71            |
| Windows OS?              |       10.0.19041           |
| Linux OS?                    |      X            |
| Visual Studio?              |    16.7.532.28833              |

Note this is in an in-process COM server.  The functions work fine when loaded as a dll from a .net application, but when running them from a VBA->COM script, there are issues.

### What is the expected behavior?
coinbaseProClient.MarketData.GetProductsAsync(), I should get all of the Products back.

### What is the actual behavior?
coinbaseProClient.MarketData.GetProductsAsync() throws an exception "The request was aborted: Could not create SSL/TLS secure channel".

### Any possible solutions?
I was able to use the solution from here:
https://stackoverflow.com/questions/2859790/the-request-was-aborted-could-not-create-ssl-tls-secure-channel

// using System.Net;
ServicePointManager.Expect100Continue = true;
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
// Use SecurityProtocolType.Ssl3 if needed for compatibility reasons

However, any ssl issues should be handled on the level of the Coinbase.Pro library. 

### How do you reproduce the issue?
Create a COM server, run GetAllProductsAsync() from a VBA script.

### Do you have a unit test that can demonstrate the bug?
No, but I can get you something to reproduce it if need be.

### Can you identify the location in the source code where the problem exists?
No.

### If the bug is confirmed, would you be willing to submit a PR?
No, this isn't really my expertise.

**Comment by bchavez** [comment]
I have no idea. The Coinbase.Pro DLL is a .NET DLL and is intended to be used in a .NET application; not necessarily used in COM.

I suspect you have some sort of infrastructural problem communicating with SSL / TLS 1.2 in COM and the issue is not really in the preview of this library.
