### ISSUE TITLE
Get all order take very long time

### ISSUE THREAD

**Issue by Marquito73** [bchavez/Coinbase.Pro#51]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| NuGet Package            |4.1.2|
| .NET Core?                   |3.1|
| Windows OS?              |Windows 10 pro|
| Visual Studio?              |Visual Studio 2019|

### What's the problem?
When I exec the GetAllOrdersAsync() method of the OrderEndpoint, it's take a long time if I don't set the limit less or equal than the number of orders in Coinbase.
If I don't set the limit or set a number greater than the numbers of orders, it's take approximately 40/50 sec.
Else almost instantly.

I try with sandbox api and without, I can get historical rates, take an order, get the current tick rate etc ..
But get all orders don't work in an acceptable time, It freeze my thread 

### What possible solutions have you considered? 
No one for now, I'm trying to find a solution to get around it

### Do you have sample code to show what you're trying to do?
My class with my method get all open orders : 
```C#
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Security.Policy;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Coinbase.Pro;
using Coinbase.Pro.Models;

namespace CoinbaseTradingBotApp.Class.Entity.CoinbaseUtility
{
    public class CoinbaseProCli
    {
        private CoinbaseProClient cbProClient = null;
        // Default currency
        public string defaultCurrency { get; private set; }
        // Url for sandbox use
        private string sandboxApiUrl = "https://api-public.sandbox.pro.coinbase.com/";

        public CoinbaseProCli(string apiKey, string apiSecret, string passPhrase, 
            string defaultCurrency, bool useSandbox = false)
        {
            //using API Key + Secret authentication
            Coinbase.Pro.Config config = new Coinbase.Pro.Config();
            config.ApiKey = apiKey;
            config.Secret = apiSecret;
            config.Passphrase = passPhrase;
            config.UseTimeApi = false;

            // Use sandbox api ?
            if (useSandbox) config.ApiUrl = this.sandboxApiUrl;

            this.cbProClient = new CoinbaseProClient(config);
            this.defaultCurrency = defaultCurrency;
        }
        
        public async Task<List<Order>> getOpenOrders(int limit = 10)
        {
            List<Order> orders = new List<Order>();

            PagedResponse<Order> lstOrders = await this.cbProClient.Orders.GetAllOrdersAsync();
            orders = lstOrders.Data;

            return orders;
        }
    }
}
```

I instanciate my object with the apiKey, apiSecret, passphrase, a defaultCurrency (not very important for now), and if I use sandbox, for change the ApiUrl.

I also try with create the URL like you create for get all orders (using Flurl), but don't work too

Have you an idea why I don't make properly, or what cause or what causes this slowness ?

Tell me if you are others questions, I am really blocked by this

Thank you in advance, and please apologize my english please, I'm French :)

**Comment by bchavez** [comment]
Hm. I don't know. You'll have to provide more diagnostic information and perform more debugging to find the cause of the slowness.

One thing you might want to try is setup Fiddler debugging with the Coinbase.Pro library. See here: https://github.com/bchavez/Coinbase/wiki/Debugging-with-Fiddler

Once you have Fiddler set up, the call to enable Fiddler debugging with Coinbase.Pro is something like:

```csharp
var client = new Coinbase.Pro.CoinbaseProClient();
client.EnableFiddlerDebugProxy("http://localhost.:8888");
```

Then you should be able to determine if it's the client or the server that's taking a long time to process your message as you'll be able to time when network requests happen.

If you can identify the problem with the library, please feel free to re-open the issue.

Thanks,
Brian

**Comment by Marquito73** [comment]
Hello,

Thank you a lot for this very usefull tool.
I use it with setup 
```C#
client.EnableFiddlerDebugProxy("http://localhost.:8888");
```
just before the line
```C#
PagedResponse<Order> lstOrders = await this.cbProClient.Orders.GetAllOrdersAsync();
```
And they is what I see with Fiddler : 36.827 ms of duration

![The Fiddler debug screen for get all orders request](https://user-images.githubusercontent.com/52123012/122674454-98feb280-d1d5-11eb-8d31-ebd5485f4c31.png)

Thank you for your time !
