### ISSUE TITLE
Reference of issue #51

### ISSUE THREAD

**Issue by Marquito73** [bchavez/Coinbase.Pro#52]
Hello,

I reopen for the #51 issue with more informations (tell me if you want more).

Thank you a lot for this very usefull tool.
I use it with setup 
```C#
client.EnableFiddlerDebugProxy("http://localhost.:8888");
```
just before the line
```C#
PagedResponse<Order> lstOrders = await this.cbProClient.Orders.GetAllOrdersAsync();
```
And that's what I see with Fiddler : 36.827 ms of duration

![The Fiddler debug screen for get all orders request](https://user-images.githubusercontent.com/52123012/122674454-98feb280-d1d5-11eb-8d31-ebd5485f4c31.png)

Thank you for your time !

_Originally posted by @Marquito73 in https://github.com/bchavez/Coinbase.Pro/issues/51#issuecomment-864548539_

**Comment by bchavez** [comment]
That looks like `36,827 ms` (thirty-six **_thousand_** milliseconds) not `36.827 ms`. That means the server took 36 seconds to respond to your request. Looks like most of the time of the request was spent processing your HTTP request on the server-side.

I do not work for Coinbase and I did not program their server-side API, you will have to ask Coinbase Support why the request took so long. I do not have access to their server-side code and I cannot help.

In the future, please do not create a new GitHub issue, you can still post comments in Issue #51 to keep information together.

**Comment by Marquito73** [comment]
Im sorry for the new issue, I'm new on GitHub, thanks for the tips.

I ask to coinbase, thank you for your fast response !
