### ISSUE TITLE
Fills.GetFillsByOrderIdAsync(orderId) returns string for Fill.Size instead of Numeric Type

### ISSUE THREAD

**Issue by pseabury** [bchavez/Coinbase.Pro#55]
### Version Information
Coinbase.Pro 4.1.2

### What is the expected behavior?
Fills should return a Numeric type for Fill.Size

### What is the actual behavior?
Fill.Size returns a string

### Any possible solutions?
Change the property to a numeric type and parse it from the response.

```
var fills = _coinbaseProClient.Fills.GetFillsByOrderIdAsync(order.Id).Result.Data;
decimal fillSize = fills.First().Size; // ERROR string != decimal
```

**Comment by bchavez** [comment]
Yea, seems `size` is defined as a string in the response.

![image](https://user-images.githubusercontent.com/478118/145683602-6f2c28a5-20eb-498c-a29c-a68dbe8111ab.png)

If you want a decimal/money/numeric type; feel free to create an extension helper method on the `Fill` return type for your specific use case in your application.
