### ISSUE TITLE
Retrieving complete price history for a product

### ISSUE THREAD

**Issue by dharmatech** [bchavez/Coinbase.Pro#57]
Hey y'all!

Not really an issue or question. Just wanted to share an approach I'm taking to retrieve the complete price history for a product (BTC-USD for example).

I have an interactive C# notebook here which demonstrates the approach:

https://github.com/dharmatech/coinbase-pro-bchavez-price-history/blob/master/coinbase-pro-bchavez-price-history.ipynb

Here's a video walkthrough of the notebook:

https://www.youtube.com/watch?v=Xl5vx9XFKyo

If there's a better approach to doing this, feel free to share below.

Thanks!

And thank you @bchavez for the awesome package!

**Comment by bchavez** [comment]
great job! thanks for posting the details. I'm sure this will help someone. Also, I enabled the discussions tab in the repo; so you don't need to create GitHub issues anymore and your discussion can stay open without me "closing" an issue:
* https://github.com/bchavez/Coinbase.Pro/discussions
Again, great work. Thanks for posting all the details!
