### ISSUE TITLE
General question regarding creating a CoinbaseProClient

### ISSUE THREAD

**Issue by hammelbeck** [bchavez/Coinbase.Pro#59]
Problem description: On this page https://github.com/bchavez/Coinbase.Pro you have an example on how
to create a pro-client. The API-Key and API-Secret will be provided by Coinbase, however it is not clear for me how to get or create the "Passphrase". Could you please provide an example on how the passphrase can be created or from where it can be obtained. Many greetings in advance. 
Regards, Henry-JP

**Comment by bchavez** [comment]
The passphrase is part of generating the API key:

https://public.sandbox.pro.coinbase.com/profile/api

![image](https://user-images.githubusercontent.com/478118/145681692-2f4e3eb5-f2f1-4097-ba1c-fd66393c3d79.png)

![image](https://user-images.githubusercontent.com/478118/145681677-ec6b967b-f671-4dc9-a9ac-ac86d5e04016.png)
