### ISSUE TITLE
Parsing Nulls

### ISSUE THREAD

**Issue by cduvall** [bchavez/Coinbase.Pro#6]
In production data, there are some markets that return with no volume, but are still listed as  valid coinbase products.  These have **null** values for the best bid and ask values on the ticker event.

`{"type":"ticker","product_id":"ZIL-USDC","price":0,"open_24h":0,"volume_24h":0,"low_24h":0,"high_24h":0,"volume_30d":0,"best_bid":null,"best_ask":null}`

This causes a serialization exception.

> Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Decimal'

**Comment by cduvall** [comment]
Yeah - those are the only ones I've detected thus far.

**Comment by bchavez** [comment]
Okay cool.

A new release `v2.0.4` with the fix should be available for download soon: https://www.nuget.org/packages/Coinbase.Pro/2.0.4

Let me know if that works!

Thanks,  
Brian
